module-name: runtime-watcher
kind: kcp
checkmarx-one:
  preset: go-default
  exclude:
    - "**/*_test.go"
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/runtime-watcher:2.1.4
  - europe-docker.pkg.dev/kyma-project/prod/runtime-watcher:latest
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
