apiVersion: component.kyma-project.io/v1alpha1
kind: Watcher
metadata:
  name: watcher-compass-sample
  labels:
    "operator.kyma-project.io/managed-by": "comapss-operator"
spec:
  serviceInfo:
    servicePort: 8082
    serviceName: "compass-event-service"
    serviceNamespace: "default"
  labelsToWatch:
    "compass-watching": "true"
  subresourceToWatch: "Status"
---
