# -- Side car to mount admission review
sidecar: true
# -- Replicas
replicas: 1
image: 
  # -- Image repository
  # repository: adityabhatia
  name: "<your-image-name>"
  # -- Image tag
  tag: "0.1.1"
  # -- Image pull policy
  pullPolicy: "Always"
# -- Image pull secrets
imagePullSecrets: []
# -- Pod security content
podSecurityContext: {}
# -- Node selector
nodeSelector: {}
# -- Affinity settings
affinity: {}
# -- Tolerations
tolerations: []
# -- Priority class
priorityClassName: ""
# -- Security context
securityContext: {}
resources:
  limits:
    # -- Memory limit
    memory: 200Mi
    # -- CPU limit
    cpu: 0.1
  requests:
    # -- Memory request
    memory: 20Mi
    # -- CPU request
    cpu: 0.01
# -- Service port
service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 443
  # -- Target port
  targetPort: 8443
  # -- Target port
  contactVersion: v1
kcp:
  loadbalancerIP: host.k3d.internal
  loadbalancerPort: 9080