apiVersion: v1
kind: ConfigMap
metadata:
  name: skr-webhook-resource-mapping
  namespace: default
  labels:
    app: kyma
data:
  kyma: |-
    group: operator.kyma-project.io
    version: v1alpha1
    kind: Kyma
  resources: |-
    - group: component.kyma-project.io
      version: v1alpha1
      kind: Manifest
      spec: true
      status: false
    - group: operator.kyma-project.io
      version: v1alpha1
      kind: Kyma
      spec: true
      status: true
