name: build-runtime-watcher

on:
  push:
    branches:
      - main  # This will get tagged with `latest` and `v{{DATE}}-{{COMMIT_HASH_SHORT}}`
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  compute-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Echo the tag
        run: echo ${{ steps.get_tag.outputs.TAG }}
  build-image:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: runtime-watcher
      dockerfile: ./runtime-watcher/Dockerfile
      context: ./runtime-watcher
      tags: ${{ needs.compute-tag.outputs.tag }}
